name: test & deploy
on:
  push:
    branches:
      - main
jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - name: hello
        run: echo "🎉 job triggered by a ${{ github.event_name }} to ${{ github.ref }}"

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout and clone repo
        uses: actions/checkout@v2

      - name: install dependencies
        run: npm ci

      - name: run unit tests
        run: npm t unit-tests

  integration-tests:
    runs-on: ubuntu-latest
    needs: unit-tests
    steps:
      - name: checkout and clone repo
        uses: actions/checkout@v2

      - name: setup postgres
        uses: harmon758/postgresql-action@v1
        with:
          postgresql db: github_actions_db
          postgresql user: github_actions_user
          postgresql password: github_actions_pw

      - name: install dependencies
        run: npm ci

      - name: run integration tests
        run: PGDATABASE=github_actions_db PGUSER=github_actions_user PGPASSWORD=github_actions_pw npm t integration-tests

  deploy:
    runs-on: ubuntu-latest
    needs: integration-tests
    steps:
      - name: checkout and clone repo
        uses: actions/checkout@v2

      - name: deploy to heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
